// AUTO-GENERATED by scripts/upload-poem-wall.mjs — do not edit by hand.
// The poem archive from @nanda.regine, clustered into poems (Instagram carousels
// = one multi-page poem). Cloudinary public_ids; CldImage delivers WebP.

export type WallPoemKind = 'art' | 'carousel' | 'single';

export interface WallPoem {
  id: string;
  kind: WallPoemKind;
  pages: string[]; // Cloudinary public_ids, in reading order
}

export const POEM_WALL: WallPoem[] = [
  {
    "id": "art-01",
    "kind": "art",
    "pages": [
      "creativelynanda/poem-wall/art-01-p01"
    ]
  },
  {
    "id": "art-02",
    "kind": "art",
    "pages": [
      "creativelynanda/poem-wall/art-02-p01"
    ]
  },
  {
    "id": "art-03",
    "kind": "art",
    "pages": [
      "creativelynanda/poem-wall/art-03-p01"
    ]
  },
  {
    "id": "art-04",
    "kind": "art",
    "pages": [
      "creativelynanda/poem-wall/art-04-p01"
    ]
  },
  {
    "id": "art-05",
    "kind": "art",
    "pages": [
      "creativelynanda/poem-wall/art-05-p01"
    ]
  },
  {
    "id": "art-06",
    "kind": "art",
    "pages": [
      "creativelynanda/poem-wall/art-06-p01"
    ]
  },
  {
    "id": "art-07",
    "kind": "art",
    "pages": [
      "creativelynanda/poem-wall/art-07-p01"
    ]
  },
  {
    "id": "art-08",
    "kind": "art",
    "pages": [
      "creativelynanda/poem-wall/art-08-p01"
    ]
  },
  {
    "id": "art-09",
    "kind": "art",
    "pages": [
      "creativelynanda/poem-wall/art-09-p01"
    ]
  },
  {
    "id": "art-10",
    "kind": "art",
    "pages": [
      "creativelynanda/poem-wall/art-10-p01"
    ]
  },
  {
    "id": "c-20240217-100644",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240217-100644-p01",
      "creativelynanda/poem-wall/c-20240217-100644-p02",
      "creativelynanda/poem-wall/c-20240217-100644-p03",
      "creativelynanda/poem-wall/c-20240217-100644-p04",
      "creativelynanda/poem-wall/c-20240217-100644-p05",
      "creativelynanda/poem-wall/c-20240217-100644-p06",
      "creativelynanda/poem-wall/c-20240217-100644-p07",
      "creativelynanda/poem-wall/c-20240217-100644-p08",
      "creativelynanda/poem-wall/c-20240217-100644-p09",
      "creativelynanda/poem-wall/c-20240217-100644-p10"
    ]
  },
  {
    "id": "c-20240217-100651",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240217-100651-p01",
      "creativelynanda/poem-wall/c-20240217-100651-p02",
      "creativelynanda/poem-wall/c-20240217-100651-p03",
      "creativelynanda/poem-wall/c-20240217-100651-p04",
      "creativelynanda/poem-wall/c-20240217-100651-p05",
      "creativelynanda/poem-wall/c-20240217-100651-p06",
      "creativelynanda/poem-wall/c-20240217-100651-p07",
      "creativelynanda/poem-wall/c-20240217-100651-p08",
      "creativelynanda/poem-wall/c-20240217-100651-p09",
      "creativelynanda/poem-wall/c-20240217-100651-p10"
    ]
  },
  {
    "id": "c-20231108-190139",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20231108-190139-p01",
      "creativelynanda/poem-wall/c-20231108-190139-p02",
      "creativelynanda/poem-wall/c-20231108-190139-p03",
      "creativelynanda/poem-wall/c-20231108-190139-p04",
      "creativelynanda/poem-wall/c-20231108-190139-p05",
      "creativelynanda/poem-wall/c-20231108-190139-p06",
      "creativelynanda/poem-wall/c-20231108-190139-p07",
      "creativelynanda/poem-wall/c-20231108-190139-p08"
    ]
  },
  {
    "id": "c-20231108-190726",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20231108-190726-p01",
      "creativelynanda/poem-wall/c-20231108-190726-p02",
      "creativelynanda/poem-wall/c-20231108-190726-p03",
      "creativelynanda/poem-wall/c-20231108-190726-p04",
      "creativelynanda/poem-wall/c-20231108-190726-p05",
      "creativelynanda/poem-wall/c-20231108-190726-p06",
      "creativelynanda/poem-wall/c-20231108-190726-p07",
      "creativelynanda/poem-wall/c-20231108-190726-p08"
    ]
  },
  {
    "id": "c-20240204-084540",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240204-084540-p01",
      "creativelynanda/poem-wall/c-20240204-084540-p02",
      "creativelynanda/poem-wall/c-20240204-084540-p03",
      "creativelynanda/poem-wall/c-20240204-084540-p04",
      "creativelynanda/poem-wall/c-20240204-084540-p05",
      "creativelynanda/poem-wall/c-20240204-084540-p06",
      "creativelynanda/poem-wall/c-20240204-084540-p07",
      "creativelynanda/poem-wall/c-20240204-084540-p08"
    ]
  },
  {
    "id": "c-20240304-094357",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240304-094357-p01",
      "creativelynanda/poem-wall/c-20240304-094357-p02",
      "creativelynanda/poem-wall/c-20240304-094357-p03",
      "creativelynanda/poem-wall/c-20240304-094357-p04",
      "creativelynanda/poem-wall/c-20240304-094357-p05",
      "creativelynanda/poem-wall/c-20240304-094357-p06",
      "creativelynanda/poem-wall/c-20240304-094357-p07",
      "creativelynanda/poem-wall/c-20240304-094357-p08"
    ]
  },
  {
    "id": "c-20240202-122635",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240202-122635-p01",
      "creativelynanda/poem-wall/c-20240202-122635-p02",
      "creativelynanda/poem-wall/c-20240202-122635-p03",
      "creativelynanda/poem-wall/c-20240202-122635-p04",
      "creativelynanda/poem-wall/c-20240202-122635-p05",
      "creativelynanda/poem-wall/c-20240202-122635-p06",
      "creativelynanda/poem-wall/c-20240202-122635-p07"
    ]
  },
  {
    "id": "c-20240522-152146",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240522-152146-p01",
      "creativelynanda/poem-wall/c-20240522-152146-p02",
      "creativelynanda/poem-wall/c-20240522-152146-p03",
      "creativelynanda/poem-wall/c-20240522-152146-p04",
      "creativelynanda/poem-wall/c-20240522-152146-p05",
      "creativelynanda/poem-wall/c-20240522-152146-p06",
      "creativelynanda/poem-wall/c-20240522-152146-p07"
    ]
  },
  {
    "id": "c-20240318-182701",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240318-182701-p01",
      "creativelynanda/poem-wall/c-20240318-182701-p02",
      "creativelynanda/poem-wall/c-20240318-182701-p03",
      "creativelynanda/poem-wall/c-20240318-182701-p04",
      "creativelynanda/poem-wall/c-20240318-182701-p05",
      "creativelynanda/poem-wall/c-20240318-182701-p06"
    ]
  },
  {
    "id": "c-20240612-084008",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240612-084008-p01",
      "creativelynanda/poem-wall/c-20240612-084008-p02",
      "creativelynanda/poem-wall/c-20240612-084008-p03",
      "creativelynanda/poem-wall/c-20240612-084008-p04",
      "creativelynanda/poem-wall/c-20240612-084008-p05",
      "creativelynanda/poem-wall/c-20240612-084008-p06"
    ]
  },
  {
    "id": "c-20240102-132030",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240102-132030-p01",
      "creativelynanda/poem-wall/c-20240102-132030-p02",
      "creativelynanda/poem-wall/c-20240102-132030-p03",
      "creativelynanda/poem-wall/c-20240102-132030-p04",
      "creativelynanda/poem-wall/c-20240102-132030-p05"
    ]
  },
  {
    "id": "c-20240204-084535",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240204-084535-p01",
      "creativelynanda/poem-wall/c-20240204-084535-p02",
      "creativelynanda/poem-wall/c-20240204-084535-p03",
      "creativelynanda/poem-wall/c-20240204-084535-p04",
      "creativelynanda/poem-wall/c-20240204-084535-p05"
    ]
  },
  {
    "id": "c-20240313-111420",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240313-111420-p01",
      "creativelynanda/poem-wall/c-20240313-111420-p02",
      "creativelynanda/poem-wall/c-20240313-111420-p03",
      "creativelynanda/poem-wall/c-20240313-111420-p04",
      "creativelynanda/poem-wall/c-20240313-111420-p05"
    ]
  },
  {
    "id": "c-20240523-111254",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240523-111254-p01",
      "creativelynanda/poem-wall/c-20240523-111254-p02",
      "creativelynanda/poem-wall/c-20240523-111254-p03",
      "creativelynanda/poem-wall/c-20240523-111254-p04",
      "creativelynanda/poem-wall/c-20240523-111254-p05"
    ]
  },
  {
    "id": "c-20231109-074633",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20231109-074633-p01",
      "creativelynanda/poem-wall/c-20231109-074633-p02",
      "creativelynanda/poem-wall/c-20231109-074633-p03",
      "creativelynanda/poem-wall/c-20231109-074633-p04"
    ]
  },
  {
    "id": "c-20240315-034301",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240315-034301-p01",
      "creativelynanda/poem-wall/c-20240315-034301-p02",
      "creativelynanda/poem-wall/c-20240315-034301-p03",
      "creativelynanda/poem-wall/c-20240315-034301-p04"
    ]
  },
  {
    "id": "c-20240719-080808",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240719-080808-p01",
      "creativelynanda/poem-wall/c-20240719-080808-p02",
      "creativelynanda/poem-wall/c-20240719-080808-p03",
      "creativelynanda/poem-wall/c-20240719-080808-p04"
    ]
  },
  {
    "id": "c-20240719-170152",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240719-170152-p01",
      "creativelynanda/poem-wall/c-20240719-170152-p02",
      "creativelynanda/poem-wall/c-20240719-170152-p03",
      "creativelynanda/poem-wall/c-20240719-170152-p04"
    ]
  },
  {
    "id": "c-20240203-100542",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240203-100542-p01",
      "creativelynanda/poem-wall/c-20240203-100542-p02",
      "creativelynanda/poem-wall/c-20240203-100542-p03"
    ]
  },
  {
    "id": "c-20240204-084534",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240204-084534-p01",
      "creativelynanda/poem-wall/c-20240204-084534-p02",
      "creativelynanda/poem-wall/c-20240204-084534-p03"
    ]
  },
  {
    "id": "c-20240206-124332",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240206-124332-p01",
      "creativelynanda/poem-wall/c-20240206-124332-p02",
      "creativelynanda/poem-wall/c-20240206-124332-p03"
    ]
  },
  {
    "id": "c-20240210-102449",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240210-102449-p01",
      "creativelynanda/poem-wall/c-20240210-102449-p02",
      "creativelynanda/poem-wall/c-20240210-102449-p03"
    ]
  },
  {
    "id": "c-20240319-155643",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240319-155643-p01",
      "creativelynanda/poem-wall/c-20240319-155643-p02",
      "creativelynanda/poem-wall/c-20240319-155643-p03"
    ]
  },
  {
    "id": "c-20240229-112429",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240229-112429-p01",
      "creativelynanda/poem-wall/c-20240229-112429-p02"
    ]
  },
  {
    "id": "c-20231028-123300",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20231028-123300-p01"
    ]
  },
  {
    "id": "c-20240612-084007",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240612-084007-p01"
    ]
  },
  {
    "id": "c-20240712-102603",
    "kind": "carousel",
    "pages": [
      "creativelynanda/poem-wall/c-20240712-102603-p01"
    ]
  }
];

export const POEM_WALL_COUNT = 37;
